# fly.toml app configuration file generated for veranstaltungs-crawler-frosty-cloud-8887 on 2025-08-05T21:54:44+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'veranstaltungs-crawler-frosty-cloud-8887'
primary_region = 'ams'

[build]
  dockerfile = "python_app/Dockerfile"
  context = "python_app"

[http_service]
  internal_port = 5000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
